#!/bin/bash
NERDCTL_VERSION=1.0.0 # see https://github.com/containerd/nerdctl/releases for the latest release
CNI_VERSION=1.1.1 # see https://github.com/containerd/nerdctl/releases for the latest release
archType="amd64"

python3 $(pwd)/get-pip.py
pip3 install -r $(pwd)/requirements.txt

wget -q "https://github.com/containerd/nerdctl/releases/download/v${NERDCTL_VERSION}/nerdctl-full-${NERDCTL_VERSION}-linux-${archType}.tar.gz" -O /tmp/nerdctl.tar.gz
tar -C /usr/bin/ -xzf /tmp/nerdctl.tar.gz --strip-components 1 bin/nerdctl

wget -q "https://github.com/containernetworking/plugins/releases/download/v${CNI_VERSION}/cni-plugins-linux-${archType}-v${CNI_VERSION}.tgz" -O /tmp/cni-plugins.tgz
mkdir -p /opt/cni/bin/
tar -C /opt/cni/bin/ -xzf /tmp/cni-plugins.tgz

# python3, pip3, nerdctl (https://github.com/containerd/nerdctl), cni plugin (https://github.com/containernetworking/plugins)
